Repository peuks/annonces, pull requests merged in 2021-09, with the labels that each got.

#2 [FIX] Set a default size to pictures in SlidePicture component
  src/components/ImageSlider.js
Labels: fix

#3 [ADD] responsive annonce detail, globalStyle h3 color, BEM image slid…
  src/components/AnnonceDetail.js
  src/components/GlobalStyles.js
  src/components/ImageSlider.js
  src/components/Scoring.js
  src/pages/Annonces.js
Labels: bug, enhancement, fix

#5 Feature/pop up
  src/App.js
  src/components/Accreditation.js
  src/components/Button.js
  src/components/ConnectionCandidature.js
  src/components/ContactProp.js
  src/components/GlobalStyles.js
  src/components/ValidationCandidature.js
  src/pages/AnnonceDetails.js
Labels: bug, enhancement, help wanted, invalid

#7 Bug/annonces2
  EHOH.js
  src/components/Accreditation.js
  src/components/AnnonceDetail.js
  src/components/ConnectionCandidature.js
  src/components/ContactProp.js
  src/components/ImageSlider.js
  src/components/SVG.js
  src/components/Scoring.js
  src/components/ValidationCandidature.js
  src/pages/AnnonceDetails.js
Labels: bug, enhancement, help wanted
